# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varEmail', models.EmailField(max_length=254)),
                ('varName', models.CharField(max_length=30)),
                ('varUser', models.CharField(max_length=30)),
                ('varTimestamp', models.DateTimeField(auto_now_add=True)),
                ('varUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
