# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join', '0002_auto_20160126_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='varName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='join',
            name='varUser',
            field=models.CharField(max_length=30),
        ),
    ]
